#!/bin/bash
# Autonomous development loop for OpenClaw
# Generates up to 5 PRs per day based on repo analysis

set -e

MAX_PRS_PER_DAY=5
SCAN_INTERVAL=3600  # 1 hour
PR_COUNT_FILE="$HOME/.openclaw/autodev-pr-count.txt"
LAST_RESET_FILE="$HOME/.openclaw/autodev-last-reset.txt"

echo "🤖 Autodevelop loop starting..."
echo "Max PRs/day: $MAX_PRS_PER_DAY"
echo "Scan interval: ${SCAN_INTERVAL}s"

# Initialize counters
touch "$PR_COUNT_FILE"
touch "$LAST_RESET_FILE"

function reset_daily_counter() {
  local today=$(date +%Y-%m-%d)
  local last_reset=$(cat "$LAST_RESET_FILE" 2>/dev/null || echo "never")
  
  if [ "$today" != "$last_reset" ]; then
    echo "0" > "$PR_COUNT_FILE"
    echo "$today" > "$LAST_RESET_FILE"
    echo "📅 Daily PR counter reset for $today"
  fi
}

function get_pr_count() {
  cat "$PR_COUNT_FILE" 2>/dev/null || echo "0"
}

function increment_pr_count() {
  local current=$(get_pr_count)
  echo $((current + 1)) > "$PR_COUNT_FILE"
}

function analyze_repo() {
  # Use OpenClaw to analyze repo and suggest improvements
  echo "🔍 Analyzing Evez666 repo..."
  
  # Check for common improvement opportunities
  local suggestions=()
  
  # Missing tests?
  if [ ! -d "tests" ] && [ ! -d "test" ]; then
    suggestions+=("add-tests:Add comprehensive test suite")
  fi
  
  # Missing docs?
  if [ ! -f "docs/API.md" ]; then
    suggestions+=("add-api-docs:Document API endpoints")
  fi
  
  # Type safety?
  if grep -r "any" circuit/*.ts 2>/dev/null | grep -v "node_modules" | wc -l | grep -q "^[1-9]"; then
    suggestions+=("fix-types:Replace 'any' types with proper types")
  fi
  
  # Performance?
  if grep -r "console.log" circuit/*.ts 2>/dev/null | grep -v "node_modules" | wc -l | grep -q "^[5-9]\|^[0-9][0-9]"; then
    suggestions+=("optimize-logging:Replace console.log with proper logger")
  fi
  
  # Security?
  if grep -r "http://" . 2>/dev/null | grep -v "node_modules" | grep -v ".git" | wc -l | grep -q "^[1-9]"; then
    suggestions+=("fix-http:Upgrade HTTP to HTTPS")
  fi
  
  echo "${suggestions[@]}"
}

function create_improvement_pr() {
  local suggestion=$1
  local type=$(echo "$suggestion" | cut -d: -f1)
  local description=$(echo "$suggestion" | cut -d: -f2-)
  
  echo "🔨 Creating PR: $description"
  
  # Create a branch
  local branch_name="autodev/$type-$(date +%s)"
  git checkout -b "$branch_name" 2>/dev/null || true
  
  # Use OpenClaw to generate changes
  case "$type" in
    add-tests)
      # Ask OpenClaw to write tests
      openclaw exec "Create unit tests for circuit/recursion-loop/recursion-loop.ts" || true
      ;;
    add-api-docs)
      # Generate API docs
      openclaw exec "Document all HTTP endpoints in circuit/spine-http-server.ts" || true
      ;;
    fix-types)
      # Fix TypeScript types
      openclaw exec "Replace 'any' types with proper TypeScript types in circuit/" || true
      ;;
    optimize-logging)
      # Add proper logger
      openclaw exec "Replace console.log with winston logger" || true
      ;;
    fix-http)
      # Upgrade to HTTPS
      openclaw exec "Replace HTTP URLs with HTTPS equivalents" || true
      ;;
  esac
  
  # Commit if changes exist
  if ! git diff --quiet; then
    git add .
    git commit -m "autodev: $description

Generated by OpenClaw autodevelop loop.
Safe mode: enabled, reviewed by DeepClaw."
    
    # Push and create PR (if GITHUB_TOKEN exists)
    if [ -n "$GITHUB_TOKEN" ]; then
      git push origin "$branch_name" 2>/dev/null || true
      
      # Create PR via gh CLI
      gh pr create \
        --title "[Autodev] $description" \
        --body "Autonomous improvement proposed by OpenClaw.

**Type**: $type
**Safe Mode**: Enabled
**Review**: Required before merge

Generated at: $(date -u +%Y-%m-%dT%H:%M:%SZ)" \
        --base main \
        --head "$branch_name" 2>/dev/null || echo "⚠️ PR creation failed (gh CLI may not be available)"
    fi
  else
    echo "ℹ️ No changes generated, skipping PR"
  fi
  
  # Return to main
  git checkout main 2>/dev/null || true
}

while true; do
  reset_daily_counter
  
  PR_COUNT=$(get_pr_count)
  
  if [ "$PR_COUNT" -lt "$MAX_PRS_PER_DAY" ]; then
    echo "📊 Current PRs today: $PR_COUNT / $MAX_PRS_PER_DAY"
    
    # Analyze repo
    suggestions=($(analyze_repo))
    
    if [ ${#suggestions[@]} -gt 0 ]; then
      # Pick random suggestion
      suggestion=${suggestions[$RANDOM % ${#suggestions[@]}]}
      
      echo "💡 Selected improvement: $suggestion"
      
      # Create PR
      create_improvement_pr "$suggestion"
      increment_pr_count
      
      echo "✅ PR created, new count: $(get_pr_count) / $MAX_PRS_PER_DAY"
    else
      echo "✨ No improvements needed right now"
    fi
  else
    echo "⏸️ Daily PR limit reached ($MAX_PRS_PER_DAY), waiting for reset"
  fi
  
  echo "💤 Sleeping for ${SCAN_INTERVAL}s..."
  sleep "$SCAN_INTERVAL"
done